### ISSUE TITLE
Tracer: исправить вывод enum'ов для результатов

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/rdo-xtext#11]
Сейчас выводится номером вместо имени.

**Comment by bogachev-pa** [comment]
@k-alexandrovsky
Кирилл, можешь объяснить, почему ты именно так записываешь структуру модели для результатов?

Например, код модели:
```
$Results
	Test_1 : watch_par Парикмахер_1.состояние_парикмахера
$End
```

В JSON структуре в `...Model.java` получаем:
```java
...
.put
(
"results", new JSONArray()
	.put
		(
			new JSONObject()
				.put("name", "model_test_7.Test_1")
				.put("type", "watch_par")
				.put("value_type", "model_test_7.Парикмахеры.состояние_парикмахера_enum")
		)

...
```

Здесь `value_type` это `model_test_7.Парикмахеры.состояние_парикмахера_enum`.

А в параметрах типа `Парикмахеры` в структуре:
```java
		.put
		(
			"parameters", new JSONArray()
				.put
				(
					new JSONObject()
						.put("name", "состояние_парикмахера")
						.put("type", "enum")
						.put
						(
							"enums", new JSONArray()
								.put("Свободен")
								.put("Занят")
						)
						.put("enum_origin", "model_test_7.Парикмахеры.состояние_парикмахера")
						.put("offset", 0)
				)
```

Здесь `type` это  просто `enum` и еще есть дополнительная информация в виде `enum_origin`.

Мне непонятно, как мне добраться до информации о енуме из JSON-структуры результата (например, чтобы вывести его строкой в трассировке). Если бы мы в результате записывали `enum_origin`, то всё было бы очевидно. А здесь мы пишем какую-то странную строчку, из которой, конечно, можно получить нужный `enum_origin`, отбросив `_enum`, но это выглядит ужасно костыльно.

**Comment by bogachev-pa** [comment]
Пока что накостылил, как описал выше.

**Comment by bogachev-pa** [comment]
Кстати, смержился с тобой, и модели вообще сыпятся на сериализации результатов типа enum.

Ты генеришь в `Имя_результата.java` вот такие куски кода:
```java
private model_test_7.Парикмахеры.состояние_парикмахера_enum minValue = model_test_7.Парикмахеры.состояние_парикмахера_enum.MAX_VALUE;
	private model_test_7.Парикмахеры.состояние_парикмахера_enum maxValue = model_test_7.Парикмахеры.состояние_парикмахера_enum.MIN_VALUE;
...
	if(value < minValue)
		minValue = value;
	
	if(value > maxValue)
		maxValue = value;
...
	storelessStats.next(Simulator.getTime(), value);
```

И это все сыпит ошибками, потому что для енумов (а у тебя тип там вообще `model_test_7.Парикмахеры.состояние_парикмахера_enum`) такие методы и поля не определены.

**Comment by k-alexandrovsky** [comment]
Так, вот `java.lang.IndexOutOfBoundsException: Index: 0, Size: 0` это конечно жуткий косяк, я даже не понял, когда я это успел сломать. Это я сейчас починю. А что касается энумов, то в структуре результатов я просто забываю отрезать `_enum`. И переделаю на ту же схему, что и у параметров ресурсов ()

**Comment by k-alexandrovsky** [comment]
Так, вот `java.lang.IndexOutOfBoundsException: Index: 0, Size: 0` это, конечно, жуткий косяк, я даже не понял, когда я это успел сломать. Это я сейчас починю. А что касается энумов, то в структуре результатов я просто забываю отрезать `_enum`. И переделаю на ту же схему, что и у параметров ресурсов (с явным копированием энумов и указанием `enum_origin`, это и правда удобно, как тем, кому интересно, откуда взялся энум, так и тем, кто просто хочет его литерал). А вот что касается падений в `watch_par` и всяких `minValue`, тут мы обратимся к справке:
http://www.rdostudio.com/help/help/rdo_lang_rus/html/rdo_obj/rdo_obj_pmd.htm
Странно, что у `watch_par` не написано ничего, конечно, но вот у `watch_value`
>`watch_value <имя_типа> [NoCheck | <логическое_выражение>] <арифметическое_выражение>`
  
>`арифметическое_выражение`
Арифметическое выражение должно быть целого или вещественного типа.

**Comment by bogachev-pa** [comment]
> вот что касается падений в  watch_par  и всяких  minValue , тут мы обратимся к справке:

Странно, тогда вообще что ли результатов типа `enum` не должно быть в трассировке?

С другой стороны, что нам мешает наблюдать за параметром типа енум? Кажется вполне валидным желанием. Для них просто часть статистики не будет иметь смысла, ну и что.
Мне кажется, надо просто сделать несколько другой формат статистики для енумов и просто впилить возможность за ними наблюдать.

**Comment by k-alexandrovsky** [comment]
Блин, не успел сделать апдейт прошлому сообщению, в общем, см. выше :)

**Comment by bogachev-pa** [comment]
Угу, читаешь мысли. Вроде это не кажется сложным, можно будет и на праздниках сделать.
Я тогда свой коммит не буду ревертить.

**Comment by k-alexandrovsky** [comment]
> Я тогда свой коммит не буду ревертить.
Так, а если я изменю структуру результатов, костыль придется немного поправить.
Что нибудь в духе
```
if (valueTypeRaw == "enum")
```
Проще сделать amend тогда, мне кажется.

**Comment by bogachev-pa** [comment]
Ну можешь либо вмержить мои 4 коммита сейчас, либо я заново сделаю мерж и потом залью фикс отдельным коммитом.

Иначе у нас будут несобирающиеся коммиты, это как-то неприятно.

**Comment by k-alexandrovsky** [comment]
Так, я исправил падения. И даже накостылил красоту с `enum_origin`. Можно проверить ее в структуре результата для `get_value`. Сериализовываться это добро не будет, зато корректность можно глянуть в сгенерированном коде.

**Comment by aurusov** [comment]
Закрываем
