### ISSUE TITLE
Реализовать возможность поиска строки в выводе трассировки

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/rdo-xtext#13]
См. требования к трассировке в https://github.com/bogachev-pa/rdo-xtext/issues/2
>6 . Поддержка текстового поиска, в том числе по регулярному выражению

**Comment by bogachev-pa** [comment]
@k-alexandrovsky
Сделал простенький диалог с поиском. Выглядит примерно так:
![find-dialog](https://cloud.githubusercontent.com/assets/6528492/5631426/7fea0380-95d7-11e4-92ce-1941bfb6f333.png)

Основная проблема в том, что у меня не получается сделать так, чтобы кнопка `Find` была активной по умолчанию (по нажатию `Enter`), а не кнопка `Close`. Есть идеи, как это сделать? Всякими `setFocus()` не выходит, они возвращают `false`.

**Comment by k-alexandrovsky** [comment]
Мне кажется, что для диалога поиска где то должен лежать готовый сниппет. Но с кнопками можно посмотреть, тут должен быть как то замешан tab order, мне кажется.

**Comment by bogachev-pa** [comment]
2, 3, 4. done
1. Я так понимаю, надо использовать функцию `setTabOrder()`, но я пока не разобрался, как именно. Во всех туториалах в неё передают `Button`, но у меня это вызывает `IllegalArgumentException`.

**Comment by k-alexandrovsky** [comment]
2, 3, 4. Круто
1. А в исходниках к функции ничего путного нет?

**Comment by bogachev-pa** [comment]
1. Я понял в чем была ошибка, в коде `setTabList()` проверка на родителя, а родитель кнопки `FInd` это не общий предок, у неё нам свой `Composite` и своя `GridData`.
Тогда не очень понятно, как это должно работать, табом-то мы ходим по всем кнопкам. К слову, если нажать таб, то вы сразу попадает на кнопку `Find`, но вот если не нажимать ничего, то мы на `Close`.

**Comment by k-alexandrovsky** [comment]
Я думаю, там будет вложенный порядок. Что нибудь в духе
```
 _________________________________________
| PARENT                                  |
|                    3       1            |
|                   EEE     FFF           |
|   _______________     _______________   |
|  |  COMPOSITE 2  |   |  COMPOSITE 4  |  |
|  |               |   |               |  |
|  |   2       1   |   |   1       2   |  |
|  |  AAA     BBB  |   |  CCC     DDD  |  |
|  |_______________|   |_______________|  |
|_________________________________________|
```
И в итоге ты задашь ордер три раза. И получишь цикл в духе
```
FFF > BBB > AAA > EEE > CCC > DDD > FFF ...
```
Может я туплю, конечно, но иного выхода для этой фигни с общими предками я не вижу.

**Comment by aurusov** [comment]
Закрываем

**Comment by bogachev-pa** [comment]
Остается низкоприоритетная проблема с таб ордером.
Вынес в отдельную таску с тегом "баг".
https://github.com/bogachev-pa/rdo-xtext/issues/19
