### ISSUE TITLE
Ленивый трассировщик

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/rdo-xtext#16]
@aurusov
@k-alexandrovsky
Нужно проверить, приведет ли ленивая имплементация трассировщика (конвертация базы данных в строки на ходу при прокрутке) к увеличению производительности. Наверное, надо будет все равно вести какой-то небольшой кэш в последними распаршенными строками.

Сразу несколько проблем:
1. Некоторые записи в базе данных не являются самодостаточными в смысле их конвертации в трассировочную строку. То есть нужно знать информацию из каких-то предыдущих записей, чтобы их распарсить.
Для основного трассировщика это выражается только в отсутствии номера текущей точки принятия решений в записях `dpt search` (кроме `SB`) - но это легко поправить (и, я думаю, надо это сделать в любом случае).
А вот для легаси-трассировщика всё намного сложнее, потому что он для совместимости добавляет фейковые записи и всё такое. Либо придется его серьезно рефакторить, либо как-то умудриться работать с ним в старом режиме.
2. При поиске по трассировке придется парсить все записи заново.
3. Реализовать всякие фишки вроде фильтров будет сложнее.
4. Что тогда передавать в `ContentProvider` `RDOTraceView`? Получается, что сырой список записей из библиотеки. Мне это кажется не совсем идеологически верным, но других способов не вижу.

**Comment by bogachev-pa** [comment]
>Для основного трассировщика это выражается только в отсутствии номера текущей точки принятия решений в записях dpt search (кроме SB) - но это легко поправить (и, я думаю, надо это сделать в любом случае).

Собственно, сразу и сделал.

**Comment by aurusov** [comment]
<b>1</b> Не понял пример. Разве это не нужно только Кириллу для вывода графа. Зачем это трассировщику ?
<b>2</b> Да, ничего страшного
<b>3</b> Сейчас фильтры реализованы хоть в каком-то виде ? В принципе, не вижу проблемы даже с ними
<b>4</b> Тут без кода не разобрать

**Comment by bogachev-pa** [comment]
**4**. Собственно, обсудили это с Кириллом. Чтобы не беспокоиться, что кто-то из гуи может попортить содержимое базы данных, надо просто делать его read-only. Сделал это в коммите выше.

**Comment by bogachev-pa** [comment]
Результаты тестирования.
Проводил по затраченной памяти (смотрел в htop) и времени прогона модели.
Под дочернюю JVM отвожу 1536мб оперативы (всего на ноуте 4гб). Это позволяет не упираться в GC слишком рано, но и всё же упираться в него раньше, чем начинает тормозить уже сама ОС.
Для справки, показания htop по памяти при простое:
при запущенном родительском эклипсе - 1000/3600
при запущенном дочернем эклипсе - 1500/3600

```
Число записей в БД        Ленивый трассировщик        Обычный трассировщик
  (в миллионах)          время(s)      память(mb)    время(s)       память(mb)
   
       0.1                2.0          1650/3600      2.1           1750/3600
       0.5                5.2          1800/3600      7.2           2000/3600
       1.0               10.3          2100/3600     12.1           2500/3600
       1.5               16.3          2500/3600     19.1           2800/3600
       2.1               21.2          2800/3600     29.9           3100/3600
       2.3               ----          ---------     44.9           3200/3600
       2.6               28.8          3000/3600     смерть (GC limit overhead)
       3.1               32.4          3200/3600
       3.7               38.5          3300/3600
       4.0               смерть (GC limit overhead)
```
В принципе, выигрыш по памяти примерно такой, как и ожидалось, но выигрыш по скорости прогона даже порадовал. Никаких пролагиваний при скролле и т.п. у ленивого трассировщика не наблюдается.

Имплементация ленивости для проведения теста была очень простой, но надо будет поправить многие вещи вроде выгрузки трассировки и поиска.

**Comment by aurusov** [comment]
хорошо

**Comment by bogachev-pa** [comment]
Done.

Стоит еще подумать, может теперь можно упростить систему нотификация для вывода в реальном времени, а также о взаимоотношениях обычного и легаси трассировщиков, уж больно они стали разными.

**Comment by aurusov** [comment]
Упростить - все за. Если разные, то должны ли они вообще общаться. Выглядит так, что у них только общий парсер бинарной сериализации, но даже результат разные. Есть еще-то еще общее ?

**Comment by bogachev-pa** [comment]
Общее сейчас только кэшированные данные. Можно их вынести куда-нибудь в отдельный класс и всё. А методы для парсинга все равно все оверрайдятся. И тогда можно будет убрать наследование.

**Comment by aurusov** [comment]
Согласен

**Comment by bogachev-pa** [comment]
Вынес кэшированную структуру модели в отдельный класс, и легаси-трассировщик больше не отнаследован от трассировщика.

**Comment by aurusov** [comment]
Все сделано, но надо подправить
* Не отображать постоянные ресурсы до окончания прогона при запуске в режиме без анимации
* Упростить схему нотификации
