### ISSUE TITLE
Окошко с деревом всех сериализуемых объектов

### ISSUE THREAD

**Issue by aurusov** [bogachev-pa/rdo-xtext#18]
Блокирует https://github.com/LeKaitoW/rdo-xtext/issues/5

**Comment by bogachev-pa** [comment]
@aurusov 
Я тут задумался над названиями для всех этих окон.
1. Логично будет переименовать `RDO Trace Config` -> `RDO Serialization Config`, но не будет ли это слишком сложно для восприятия пользователем? Может, переименовать в коде (так будет правильнее отражена суть), а для пользователя выводить другое название? Например, `Logging Configuration`. Ну или оставить `trace` в названии и сделать что-то вроде `Tracing Configuration`.
2. Новое окно со всеми сериализованными объектами. `Serialized Objects` кажется плохим по той же причине, что я описал выше. Может быть `Collected Data`? Но это не очень логично, потому что никакой `Data` в окне нет, там только список наименований. `Traced Objects`?

**Comment by aurusov** [comment]
1. В коде кажется правильным ```SerializationConfig```. Не надо никаких ```RDO```, это и так понятно. Окошко лучше назвать ```Monitoring Configuration```
2. Мне нравится ```Collected Objects```, ```Monitored Objects``` чуть меньше

**Comment by bogachev-pa** [comment]
1, 2. Пока использую предложенные названия.

3*.* Собственно сделал начальный вариант окошка. Сейчас я просто копирую туда соответствующий кусок дерева (т.е. отмеченный галочками и соответствующий запущенной модели) из `Monitoring Configuration`.

Вообще я очень приблизетельно себе представляю, какие именно элементы дерева нужны для построения графиков или еще для чего-то, для чего окошко будет использоваться.

На консультации еще какой-то разговор про временные ресурсы, т.е. дерево будет изменяться в процессе прогона, временные ресурсы добавляться и отмечаться, как удаленные (ну, удалять их из дерева вообще смысла нет, наверное)? В общем, хочется поподробнее понять задачу.

**Comment by aurusov** [comment]
3. Копировать ничего туда не надо, надо вытаскивать всю информацию из сериализованной базы. Представь, что тебе скинули только бинарную сериализацию и больше у тебя ничего нет. Если ты лезешь в исходники или еще куда - это неправильный источники информации, т.к. он может разъехаться с сериализованной базой. Если в базе чего не хватает, то это надо допиливать.

**Comment by bogachev-pa** [comment]
Я правильно понимаю, что окошко должно заполняться по мере появления в базе данных новых записей, так? Т.е. как только хоть одна запись, касающаяся данного объекта, появилась в БД, он должен отобразиться в дереве?

@k-alexandrovsky
Я все еще плохо понимаю индексы в базе данных, позволят ли они нам не парсить записи БД для формирования этого дерева, а только обращаться непосредственно к индексам и получать всю информацию о структуре из них?

**Comment by aurusov** [comment]
Да, это актуально для временных объектов. У БД должно быть описание структуры, из которого ты заранее сможешь узнать о том, какие ресурсы временные, а значит могут динамически появляться и удаляться.

**Comment by k-alexandrovsky** [comment]
@bogachev-pa 
Да, наш кейс - только временные ресурсы. Поэтому мы всегда можем взять мета-индекс по типу ресурса, у него получить список индексов ресурсов. Берем его размер, вуаля. Заводим мапу `<Integer, String>`, чтобы присвоить имена тем, у кого они есть. Заодно проверяем каждый индекс на `null`, потому что:
```java
while(resourceTypeIndex.resources.size() < resource.getNumber() + 1)
	resourceTypeIndex.resources.add(null);
```
Такое происходит, когда ресурс 5 сериализуется, потому что создавший его паттерн имеет право выставить ему сериализацию, а 4му ресурсу такая честь не выпала.

**Comment by bogachev-pa** [comment]
Переделал дерево так, чтобы оно формировалось на основе базы данных. Все индексы, которые использует бд, я перенес сразу в это дерево. Они же и понадобятся всяким построителям графиков и графов, так что я думаю, это удобно, что к соответствующему индексу можно будет получить доступ прямо из элемента дерева.

Насчет заполнения дерева в реальном времени, мне нужно это сейчас делать?

@k-alexandrovsky 

Не очень понимаю, насчет заполнения индексов ресурса `null`-ами. Зачем? Вместо мапы `<Integer, String>` я присваиваю имена вообще всем ресурсам (временным так, как они в трассировке выводятся, с квадратными скобками и номером). Нумерация меня больше не интересует и пропускать что-то, кажется, больше не надо.

@LeKaitoW, @kstrizhov

Теперь у рдо появилось окошко с названием `Collected Objects`, в котором в древовидной структуре отражены все объекты, записи о которых попали в базу данных в ходе прогона модели. Именно в него вам нужно добавить/перенести вызов построения графиков/графа поиска по трассировке.

Я еще чуть позже добавлю в библиотеку хелпер, чтобы предоставить для гуи более удобное апи для работы с этим деревом.

**Comment by aurusov** [comment]
>Насчет заполнения дерева в реальном времени, мне нужно это сейчас делать?

Делать нужно потому что дотянуться до временных ресурсов просто невозможно. Понятно, что начать отлаживать графики и граф DPT можно и без них. И ты можешь переключиться на другие задачи. Но эту таску закрывать без решения по временным ресурсам нельзя.

**Comment by bogachev-pa** [comment]
>Делать нужно потому что дотянуться до временных ресурсов просто невозможно.

Я немного не об этом. Временные ресурсы сейчас и так добавляются в дерево. Просто я не обновляю гуевую часть в процессе работы модели, только один раз в самом конце. Мы же не собираемся удалять временные ресурсы из дерева при удалении модели? Иначе как по ним построить графики в конце прогона.

**Comment by aurusov** [comment]
>Я немного не об этом.

Значит я не понял про что ты. Вижу противоречивые вещи, поясни.

>Насчет заполнения дерева в реальном времени, мне нужно это сейчас делать?

vs

>Временные ресурсы сейчас и так добавляются в дерево

Удалять, конечно не надо. Удаление должно быть связано с удалением (очищением) БД перед следующим запуском. Но отметить как-то, что ресурс удалён, можно.

**Comment by bogachev-pa** [comment]
Ну да, я имел в виду не заполнение дерева по ходу заполнения бд (оно происходит), а его обновлении в процессе прогона (в смысле в гуи - вот этого пока нет) при моделировании в режиме реального времени.

Отметку, думаю, можно добавить в отображаемое имя ресурса. Что-нибудь вроде `Клиент[50] (deleted)`.

**Comment by aurusov** [comment]
>Ну да, я имел в виду не заполнение дерева по ходу заполнения бд (оно происходит), а его обновлении в процессе прогона (в смысле в гуи - вот этого пока нет) при моделировании в режиме реального времени.

Все равно не понял. Нужен пример. Вот что сейчас будет, если
* временный ресурс добавился
* изменился
* удалился

Интересует взгляд с точки зрения прогона, на который мы смотрим через ГУИ. Предположим, есть только твое окно. Про бинарную БД пользователю знать не обязательно.

>Отметку, думаю, можно добавить в отображаемое имя ресурса. Что-нибудь вроде Клиент[50] (deleted)

Можно, но лучше выделить это графически, например, другой картинкой или перечеркнутым именем.

**Comment by bogachev-pa** [comment]
С точки зрения дерева (которое хранится в `rdo.lib`):
- временный ресурс добавился -> имя ресурса добавилось в дерево
- изменился -> ничего
- удалился -> ничего

С точки зрения гуи:
Оно пустое во время прогона и ему кормится сформированное дерево из `rdo.lib` по окончании прогона. Тогда пользователь получает его окончательный вариант со всеми временными ресурсами, созданными в процессе прогона.

**Comment by aurusov** [comment]
Теперь понятно. Исходим из того, дерево является штатной точкой входа для графиков и поиска (DPT search), которые мы хотим строить в процессе моделирования, а не только в конце. Поэтому обновлять ГУИ надо по мере изменения дерева (подписки рулят). Ну и для удаленных ресурсов надо пробрасывать флажок.

**Comment by aurusov** [comment]
Теперь надо допилить создание окна в начале прогона и добавление в него временных ресурсов по ходу моделирования. Паша, если задачи сложные, то эту можно закрыть и завести две новые.

**Comment by bogachev-pa** [comment]
Все готово.
Только неправильно отреференсил таску в коммите, но уже не буду амендить.

**Comment by aurusov** [comment]
Временные ресурсы появляются в окошке постепенно ? Что происходит, когда они удаляются ?

**Comment by bogachev-pa** [comment]
Да, постепенно, по мере прогона модели,
В данный момент ничего. Я подумаю, как будет симпатичнее обозначить, что он удален, и залью вариант, который мне больше понравится.

**Comment by aurusov** [comment]
Посмотри как было в старом РДО. Можно что-то своё придумать. Это единственное, что держит эту таску ?

**Comment by bogachev-pa** [comment]
Ну разве что кто-нибудь обнаружит проблемы, когда будет использовать это дерево. Функционал вроде весь готов.

**Comment by aurusov** [comment]
Отлично. Хочется закрыть таску. Нравится мне это дело :)

**Comment by bogachev-pa** [comment]
1. Сделал отображение удаленных ресурсов серым цветом и отдельной иконкой.
Сейчас иконок в дереве три вида: для вершин, у которых нет индекса, для вершин, у которых есть индекс, и отдельно для удаленных ресурсов.
2. Добавил в дерево параметры ресурсов. В индексе у них сейчас хранится только номер параметра. Список необходимых записей из базы данных я туда добавлять не стал, т.к. это дублирование списка, уже хранящегося в ресурсе.

Т.е. по пункту 2 получается два возможных подхода:

А. (сейчас реализован) Не хранить список записей в индексе параметра ресурса.
Тогда, имея `CollectedDataNode paramNode` параметра, т.е. вершину дерева, мы можем получить список всех записей, обратившись к индексу ресурса `paramNode.getParent().getIndex()`. Соответственно, чтобы что-то распрарсить, нам нужно два индекса - у индекса параметра взять его номер, а у индекса ресурса - список номеров записей.

Б. Хранить список записей и там, и там. В итоге нам не нужен индекс ресурса, чтобы что-то распарсить, но зато все данные индекса ресурса дублируются в индексах каждого из его параметра, что кажется довольно расточительным.

**Comment by bogachev-pa** [comment]
Еще добавил тип и оффсет параметра в его индекс.
Теперь, чтобы получить значение параметра в записи ресурса (`Entry.data`), не нужно итерировать по всем параметрам, достаточно просто взять у индекса параметра `type` и `offset` и прочитать нужную величину по этому оффсету.

**Comment by aurusov** [comment]
>Сделал отображение удаленных ресурсов серым цветом и отдельной иконкой. Сейчас иконок в дереве три вида: для вершин, у которых нет индекса, для вершин, у которых есть индекс, и отдельно для удаленных ресурсов.

Тот случай, когда лучше скрин добавить.

>Т.е. по пункту 2 получается два возможных подхода:

Конечно первый. Если им будет тяжело пользовваться, то подумаем над другими.

**Comment by bogachev-pa** [comment]
>Тот случай, когда лучше скрин добавить.

Как-то так это сейчас выглядит.
![collected_objects_tree](https://cloud.githubusercontent.com/assets/6528492/7113604/27c03e74-e1de-11e4-8b2c-eb39c4ada02a.png)

**Comment by aurusov** [comment]
Что-то еще осталось от задачи ?

**Comment by LeKaitoW** [comment]
Надо добавить возможность раскрытия элемента дерева по двойному клику.

**Comment by bogachev-pa** [comment]
Готово.

**Comment by aurusov** [comment]
Что-то еще осталось от задачи ?

**Comment by bogachev-pa** [comment]
Из первоначальных задач - нет.

Но я бы пока не закрывал, потому что деревом начинают активно пользоваться и Оля, и Кирилл, и могут возникнуть какие-то дополнительные требования/пожелания к дереву, которые удобно обсуждать в этой таске.

**Comment by aurusov** [comment]
Тогда лучше закрыть.

**Comment by bogachev-pa** [comment]
Окей.

**Comment by LeKaitoW** [comment]
После прогона модели с ~10000 клиентами, при попытке раскрыть в дереве список клиентов, окошко подвисает на 10-15 секунд. (На винде ещё хуже - даже запуск модели невозможен.)
Когда число клиентов достигает 28000, то возможен только Force quit.

**Comment by aurusov** [comment]
1. Про тормоза надо перенести в отдельную таску про оптимизацию
2. Оля, для тестирования графиков упрости модель: удали из неё Клиентов, как временных ресурсов. Надо, что в графике длины очереди был 1.000.000 значений, а иметь 1.000.000 клиентов-ресурсов для этого не обязательно. Если непонятно как упростить - спроси меня.

**Comment by LeKaitoW** [comment]
@aurusov 
2. Честно говоря, это не было связано с тестированием графиков - для построения графика длины очереди мне не нужно раскрывать список клиентов.

**Comment by aurusov** [comment]
@LeKaitoW 
2. Тогда можно ничего не менять. Думал, что возникли проблемы с построением графика из-за тормознутости.

**Comment by kstrizhov** [comment]
Выпилить из дерева паттерны всех типов, кроме эвентов, так как индексируются активности, реализующие паттерны, а не сами паттерны.
