### ISSUE TITLE
Трассировка

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/rdo-xtext#2]
Копипаст требований из старой таски:

Требования
1. **[suspended]** Несколько окон трассировки на экран
2. **[suspended]** Прореживание по различным критериям
3. **[done]** Спроектировать читаемый вид трассировки
4. ~~Научиться выводить трассировку по графу в виде графа~~
Выполняется @kstrizhov.
5. **[done]** Трассировка должна динамически дополняться
6. **[done]** Поддержка текстового поиска, в том числе по регулярному выражению

**Comment by bogachev-pa** [comment]
@k-alexandrovsky 
Насчет прибивания трассировки. У меня всё круто работает и не залагивает, если делать между прогонами `viewer.getTable().dispose()` и потом инициализировать весь вьюер заново.
Это очень страшно и костыльно, к тому же, я пока не могу заставить вьюер нормально отображать данные после такого испытания, пока я не подергаю окошко трассировки или не переключусь с него на другое и потом обратно.

Однако никаких тормозов при запуске следующего прогона после обильной трассировки нет. Есть идеи, как более аккуратно сэмулировать поведение `getTable().dispose()`?

**Comment by k-alexandrovsky** [comment]
Не уверен, что знаю какой нибудь способ очистки таблиц, кроме `dispose()`. По поводу дерганья окошка можно попробовать `viewer.getControl().update()` или `viewer.refresh()`. Надо играться на живом примере, конечно. Я так понимаю, сейчас это локальный код и он не закоммичен.

**Comment by bogachev-pa** [comment]
Локальный, сейчас закоммитил в отдельную ветку https://github.com/bogachev-pa/rdo-xtext/commit/f159a05b38676742d06cb00b985557487b2caa6e (он, правда, не сребейжен на последние изменения). 

Как видишь, я пробую вообще все, что можно. Может, я что-то упускаю еще?

**Comment by k-alexandrovsky** [comment]
Хм, мне кажется, тут вся загвоздка в паренте. Парент может быть не в курсе, что у него там у детей непотребство всякое творится. Надо попробовать ему вызвать все имеющие аналоги команды.

**Comment by aurusov** [comment]
Почистить заголовок задачи, Закрываем.
