### ISSUE TITLE
Имплементация новой грамматики языка

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/rdo-xtext#20]
Начало обсуждения здесь: https://github.com/k-alexandrovsky/rdo-xtext/issues/27

В шапке буду периодически обновлять код модели в текущей грамматике.

```erlang
enum Orig { TYPE1, TYPE2 }

type Foo {
	int bar;
	String str = "hello";
}

type EnumTypeTest {
	 Orig testEnum;
}
enum Client_type {Type1, Type2}
enum Barb_states {Free, Busy}
enum Client_state {Entered, Started}

type BarberShops {
	 double people_in_queue;
}

type Clients {
	Client_type client_type;
	Client_state state = Client_state.Entered;
}

type Barbers {
	Barb_states state_of_barber = Barb_states.Free;
	int people_served;
	int duration_min;
	int duration_max;
	Client_type client_type_of_client;
}

resource BarberShop = BarberShops.create(0.0);
resource Barber_1 = Barbers.create(*, 0, 20, 40, Client_type.Type1);
resource Barber_2 = Barbers.create(*, 0, 25, 70, Client_type.Type2);
resource Barber_3 = Barbers.create(*, 0, 30, 60, Client_type.Type2);
resource foo = Foo.create(5, *);
EnumTypeTest.create(Orig.TYPE1);
EnumTypeTest.create(Orig.TYPE2);

constant int x = 40;

event Pat_coming_of_client_test (int a, double b, Orig c) {
	resource _client = Clients.create(Тип_клиента.next(), *);
	_client.state = Client_state.Entered;
	Pat_coming_of_client_test.plan( currentTime + Интервал_прихода.next(), 1, 2.0, Orig.TYPE1 );
	BarberShop.people_in_queue += 1;
}

operation Pat_of_serving_of_client(int a, double b, Orig test_enum_param) {
	relevant _BarberShop = BarberShop.select(_BarberShop.people_in_queue > 0);
	relevant _Client = Clients.select(_Client.state == Client_state.Entered);
	relevant _Barber = Barbers.select(_Barber.state_of_barber == Barb_states.Free
			and _Barber.client_type_of_client == _Client.client_type)
				.withMin( _Barber.people_served);

	set duration() {
		return Длительность_обслуживания.next( _Barber.duration_min, _Barber.duration_max );
	}
	set begin() {
		_BarberShop.people_in_queue--;
		_Client.state = Client_state.Started;
		_Barber.state_of_barber = Barb_states.Busy;
	}
	set end() {
		_Barber.state_of_barber = Barb_states.Free;
		_Barber.people_served += a;
		_Client.erase();
	}
}

rule Change_string_rule() {
	relevant _Foo = Foo.select(_Foo.bar == 5);
	set execute() {
		_Foo.bar++;
		_Foo.str = "heyheyyyy";
	}
}

dpt model {
	set init() {
		setCondition(any);
		setPriority(1);
	}
	activity Serving_of_client(5) checks Pat_of_serving_of_client(15, 15.0, Orig.TYPE1);
	activity ChangeString(5) checks Change_string_rule();
}

set init() {
	Pat_coming_of_client_test.plan(currentTime + 30, 1, 2.0, Orig.TYPE1);
}

set terminateCondition() {
	return currentTime >= 60 * 24 * 10 * testFun(1, 2.0) * testTable(1) * testList(1);
}

result Busyness_of_barber_1 = watchState(Barber_1.state_of_barber == Barb_states.Busy);
result Busyness_of_barber_2 = watchState(Barber_2.state_of_barber == Barb_states.Busy);
result Busyness_of_barber_3 = watchState(Barber_3.state_of_barber == Barb_states.Busy);
result Served_by_barber_1 = getValue(Barber_1.people_served);
result Served_by_barber_2 = getValue(Barber_2.people_served);
result Served_by_barber_3 = getValue(Barber_3.people_served);

sequence Интервал_прихода = double exponential(123456789, 1/30.0);

sequence Длительность_обслуживания = double uniform(123456789);

sequence Тип_клиента = Client_type histogram(123456789) {
	Client_type.Type1 1.0
	Client_type.Type2 5.0
}

int testFun(int test1, double test2) {
	return 1;
}

int table testTable (int[1 .. 2] a) {
	1 1
	2 2
}

int list testList (int[1 .. 2] a) {
	1 = 1
}
```

**Comment by bogachev-pa** [comment]
@aurusov
@k-alexandrovsky
Залил первые изменения по грамматике.
Кирилл, было бы круто, если бы ты это поревьюил, особенно изменения в `RDO.xtext`.
На данный момент чуть усложненная (для большего покрытия грамматики) модель парикмахерской выглядит так:
```erlang
enum orig { TYPE1, TYPE2 }

type Foo {
	bar : int
	str : String = "hello"
}
type enumOrigin {
	origin : ( Type1, Type2 ) 
}

type BarberShops {
	people_in_queue : double 
}

type Clients {
	client_type : such_as enumOrigin.origin 
	state : ( Entered, Started ) 
}

type Barbers {
	state_of_barber : ( Free, Busy )  = Free
	people_served : int 
	duration_min : int 
	duration_max : int 
	client_type_of_client : such_as enumOrigin.origin 
}

resource BarberShop = BarberShops(0.0)
resource Barber_1 = Barbers(*, 0, 20, 40, Type1)
resource Barber_2 = Barbers(*, 0, 25, 70, Type2)
resource Barber_3 = Barbers(*, 0, 30, 60, Type2)
resource foo = Foo(5, *)

const int x = 40

pat Pat_coming_of_client is event() {
	relevant _BarberShop = BarberShop Keep
	relevant _Client = Clients Create
	set execute() {
		Pat_coming_of_client.planning( Time_now + Интервал_прихода(3000) );
		_BarberShop.people_in_queue++;
		_Client.client_type = Тип_клиента;
		_Client.state = Entered;
	}
}

pat Pat_of_serving_of_client is operation(a : int, b : double) {
	relevant _BarberShop = BarberShop.choose(_BarberShop.people_in_queue > 0)
		Keep NoChange
	relevant _Client = Clients.choose(_Client.state == Entered)
		Keep Erase
	relevant _Barber = Barbers.choose(_Barber.state_of_barber == Free
			and _Barber.client_type_of_client == _Client.client_type)
				.with_min( _Barber.people_served)
		Keep Keep
	set time() {
		return Длительность_обслуживания( _Barber.duration_min, _Barber.duration_max);
	}
	set begin() {
		_BarberShop.people_in_queue--;
		_Client.state = Started;
		_Barber.state_of_barber = Busy;	
	}
	set end() {
		_Barber.state_of_barber = Free;
		_Barber.people_served += a;
	}
}

pat Change_string_rule is rule() {
	relevant _Foo = Foo.choose(_Foo.bar == 5) Keep
	set execute() {
		_Foo.bar++;
		_Foo.str = "heyheyyyy";
	}
}

dpt model is some() {
	setCondition(NoCheck);
	setPriority(1);
	activity Serving_of_client(5) is Pat_of_serving_of_client(15, 15.0);
	activity ChangeString(5) is Change_string_rule;
}

set onInit() {
	Pat_coming_of_client.planning( time_now + Интервал_прихода( 30 ) );
}

set terminateCondition() {
	return Time_now >= 12 * 7 * 600 * testFun(1, 2.0) * testTable(1) * testList(1);
}

result Busy_of_barber_1 = watch_state(Barber_1.state_of_barber == Busy)
result Busy_of_barber_2 = watch_state(Barber_2.state_of_barber == Busy)
result Busy_of_barber_3 = watch_state(Barber_3.state_of_barber == Busy)
result Served_by_barber_1 = get_value(Barber_1.people_served)
result Served_by_barber_2 = get_value(Barber_2.people_served)
result Served_by_barber_3 = get_value(Barber_3.people_served)

seq double Интервал_прихода is legacy exponential(123456789)

seq double Длительность_обслуживания is legacy uniform(123456789)

seq such_as enumOrigin.origin Тип_клиента is legacy by_hist(123456789) {
	Type1 1.0
	Type2 5.0
}

fun int testFun is algorithmic(int test1, double test2) {
	return 1;
}

fun int testTable is table(int[1 .. 2] a) {
	1 1
	2 2
}

fun int testList is list(int[1 .. 2] a) {
	1 = 1
}
```

Что нужно сделать:
1. Добавить работу с енумами (сейчас эти грамматические правила никак не обрабатываются генератором).
2. Выпилить `such_as` (зависит от 1).
3. Переделать объявления параметров ресурсов и паттернов:
`name : type = default` -> `type name = default`
(зависит от 2)
4. Убрать префиксы типа `seq`, `pat` и т.п. Пока не разобрался, как это сделать с леворекурсивной грамматикой.
5. Разобраться, что делать с конверторами (`Keep`, `Create`) и т.п.
6. Как-то отделить `setCondition()` и `setPriority()` от списка активностей в дпт.
7. Придумать более логичные имена для ключевых слов.

**Comment by bogachev-pa** [comment]
1, 2, 3. Done.

**Comment by bogachev-pa** [comment]
5, 7, 10. Done.
Наиболее приоритетна сейчас задача 9.

**Comment by bogachev-pa** [comment]
@aurusov
Касательно задачи 9. У меня получилось сделать так, чтобы к енумам нужно было обращаться по полному имени (еще не пушил), но по ходу дела возникли сомнения на тему того, зачем вообще это нужно.
В старом РДО проблема была в том, что мы не могли отличить енумы один от другого. Здесь такой проблемы, насколько я понимаю, нет, мы явно понимаем, что это за енум, по типу переменной/параметра/т.п. куда мы его пишем. И в джава-коде енумы уже все правильные и никаких проблем различить их не будет. Тогда зачем нам нужны полные имена в коде на рдо? Это только перегружает модель.

Я еще проверю вечером точно, не могут ли в хитрых случаях возникнуть проблемы, но, если их не будет, предлагаю оставить относительные имена енумов.

**Comment by aurusov** [comment]
Без примера непонятно. Например, как обойтись без полного имени в этом случае при обращении к ```B``` ?
```
enum E1 {R, G, B};
enum E2 {A, B, C};
```

**Comment by bogachev-pa** [comment]
Проверил, проблем нет. Наш компилятор выражений выводит тип енума из типа левой части.
```java
E1 test_1 = B;
E2 test_2 = C;
if (test1 == B)
    test_2 = B;
```
Мы всегда можем отличить что это за енум, кроме разве что таких конструкций (наш компилятор выражений ее не осилит все равно, если только не прокачивать его координально):
```java
if (B == B)
    ...
```

Мои доводы за полные имена:
- так в джаве
- все равно мы будем использовать полные имена, когда перейдем на xbase

Доводы против:
- с полными именами модели выглядят более нагруженно и хуже читаются

**Comment by bogachev-pa** [comment]
Пока сделал полные имена. Могу добавить возможность также использовать краткие имена как раньше.

**Comment by aurusov** [comment]
>Доводы против:

Довод про читаемость весьма спорный. Да, текста явно больше, а вот читаемость может быть лучше. В C++11 появились такие енумы, так я на них РДО перевёл (https://github.com/aurusov/rdo_studio/commit/1b5f16e9bae4b7c93bdaa13d0f519b4d0eca60b3)

**Comment by bogachev-pa** [comment]
@aurusov 
Кажется, я чего-то не понимаю насчет последовательностей, а именно, почему при создании последовательности мы задаем ей только базу, а параметры передаем при вызове?
Ведь случайное распределение определеяется именно параметрами. База задает точку, с которой мы в это распределение входим.
Какой тогда смысл создавать последовательность только с базой и передавать параметры при вызове? Если передавать ей другие параметры, то мы просто будем странным образом чередовать базу для двух разных последовательностей, пропуская для каждой какие-то значения.

Не правильнее ли будет вместо:
```java
sequence int mySequence is exponential(123456789)
...
set duration() {
    return mySequence(30);
}
```
писать
```java
sequence int mySequence is exponential(123456789, 30)
...
set duration() {
    return mySequence.next();
}
```
?

**Comment by aurusov** [comment]
Да

**Comment by bogachev-pa** [comment]
Но как тогда разрешить такой случай?
```erlang
set duration() {
	return Длительность_обслуживания.next(_Barber.duration_min, _Barber.duration_max);
}
```
где `_Barber` - это подобранный ресурс? Видимо, последовательности были сделаны такими именно для этого.

Как лучше выйти из этой ситуации?
1. Вернуть как было.
2. Разрешить задавать последовательности и как было (только база, а параметры передаются в `next()`), и по-новому.
3. Придумать что-то вроде анонимных последовательностей с встроенной базой. Но не очень понятно, что делать, если пользователь захочет иметь несколько последовательностей с разными базами.

И еще вопрос, это вообще нормально, задавать последовательности какую-то базу, а потом последовательность с этой базой вызывать с разными параметрами? Т.е. если мы берем только каждое третье значение из последовательности, мы не нарушаем случайности распределения?

**Comment by aurusov** [comment]
На второе отвечу на консультации, потому что много эмоций и нет точного ответа.

Решением может быть следующее
1. Отделить метод получения uniform01() от всех остальный, ведь только ему и нужна база. В бусте это называется генераторами, их много http://www.boost.org/doc/libs/1_58_0/doc/html/boost_random/reference.html#boost_random.reference.generators
2. На основе (1) сделать законы с явным указанием параметров (как сейчас в РДО). В бусте это распределения http://www.boost.org/doc/libs/1_58_0/doc/html/boost_random/reference.html#boost_random.reference.distributions
3. На основе (2) сделать окончательные законы, которые будут доступны пользователю как можно с более простым синтаксисом ```dist.next()```. Стоит подумать в сторону генераторов или итераторов Питона для обощения.

Если не отобрать возможность изменять (1) и руками вызывать (2), то получим требуемую гибкость.

**Comment by bogachev-pa** [comment]
@aurusov 
Теперь можно сказать, что новая грамматика полностью покрывает старую по функционалу. Т.е. все валидные действия, которые могли быть сделаны в старой грамматике, могут быть сделаны и в новой.

Остались нерешенными некоторые вопросы с трассировкой, которые я хотел бы обсудить в ближайшую субботу.

**Comment by aurusov** [comment]
Отлично. Приступай к оформлению. Не хочется потерять балл из-за тормознутости при реальной работе. Эту таску закроешь, а для трассировке заведешь отдельную ?

**Comment by bogachev-pa** [comment]
Завел (https://github.com/bogachev-pa/rdo-xtext/issues/25).

Эту пока закрывать не хочу, так как в процессе написания руководства по новой грамматике, могут возникнуть какие-то еще вопросы.

**Comment by bogachev-pa** [comment]
@aurusov 
Я внезапно осознал, что раз теперь, когда ресурсы не надо подбирать, нам и не нужно пользоваться механизмом релевантных ресурсов, то для эвентов релевантные ресурсы потеряли вообще всякий смысл. В общем-то, смысла они не имели и раньше, но теперь еще и пропала надобность обзывать их релевантными.

А раз у эвента релевантных ресурсов нет, то и смысла в обертке тела эвента в виде метода `execute()` тоже нет, а значит теперь наше любимое событие прихода клиента, которое раньше выглядело вот так:
```
$Pattern Образец_прихода_клиента : event
$Relevant_resources
	_Парикмахерская: Парикмахерская Keep
$Body
_Парикмахерская:
	Convert_event
		Образец_прихода_клиента.planning( time_now + Интервал_прихода( 30 ) );
		количество_в_очереди++;
$End
```
теперь выглядит вот так:
```
event Событие_прихода_клиента()
	Событие_прихода_клиента.plan(currentTime + Интервал_прихода.next());
	Парикмахерская.количество_в_очереди++;
}
```

Все это дело навело меня на мысль, что эвенты это же вовсе не особый тип паттерна, это вообще другая сущность из другого подхода к ИМ. И потому эвент у меня больше не наследуется от паттерна, в грамматике они тоже никак не связаны, и разве что в некоторых местах в либе они еще имеют каких-то общих предков, но этот рефакторинг я закончу потом.

**Comment by bogachev-pa** [comment]
Думаю, можно уже закрыть.
