### ISSUE TITLE
Документация по новой грамматике

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/rdo-xtext#24]

**Comment by bogachev-pa** [comment]
@aurusov, @k-alexandrovsky, @LeKaitoW, @kstrizhov, @AlexChernov
Я начинаю писать руководство по новой грамматике РДО. Руководство подразумевается как замена старой справки по РДО.
Просьба ко всем, если получится найти час свободного времени, выкачать мои исходники в ветке `new_grammar` и попробовать пройти туториал. Там сейчас всего две страницы (разобраны две очень простые модели), отсутствует какой-либо дизайн и все очень минималистично.
Но хотелось бы услышать ваши мнения по поводу самой грамматики, каких-то багов (касающихся самой грамматики в первую очередь - там есть странности с гуевыми частями, но в целом все вроде работает), а также стиля написания и содержания туториала.
В данный момент туториал в среду не встроен, так что просто открывайте html-ки в папке `tutorial`.

**Comment by LeKaitoW** [comment]
1. В первом туториале приведен результат из второго.
2. Результаты в туториале отображены в текстовом формате, хотя в перспективе по умолчанию задан формат дерева. Лучше прикрепить скриншот.

**Comment by bogachev-pa** [comment]
Добавил боковую панель с содержанием, исправил опечатки.
@LeKaitoW 
1. Поправил.
2. Согласен, лучше. Надо вообще будет добавить побольше скриншотов.

**Comment by aurusov** [comment]
1 ```Содержание модели``` -> ```Постановка задачи```  (не настаиваю)

2
>Пусть в службу технической поддержки с некоторой частотой (интервал между звонками задается экспоненциальным законом с интенсивностью λ = 30) поступают звонки. Необходимо подсчитать, сколько звонков поступит за рабочий день (8 часов).

Очень длинные скобки
Пусть в службу технической поддержки с некоторой частотой поступают звонки. Интервал между звонками задается экспоненциальным законом с интенсивностью λ = 1/30 [1/мин]. Необходимо подсчитать, сколько звонков поступит за рабочий день (8 часов).

**Comment by kstrizhov** [comment]
Прочитал оба туториала.
1. Мне как-то режет глаз отсутствие точки с запятой при описании параметров ресурса
```java
type TechSupport {
    OperatorState operatorState
    int queueLength
    int peopleServed
}
```
 и ее наличие  при описании какго-нибудь метода
```java
set execute() {
    techSupport.callCount++;
    newCall.planning(currentTime + newCallInterval(30));
}
```
Не лучше ли ввести какое-то однообразие? Причем, хоть это уже и обсуждалось (ты сказал, что точка запятой не обязательна в качестве знака-разделителя), вариант с точкой запятой кажется читабельнее.
2. Аналогично режет глаз слово ключевое слово `is`. Например в случае 
```java
resource techSupport is TechSupport.create(OperatorState.FREE, 0, 0)
```
будто бы происходит инициализация переменной (хоть это и не совсем так) вызовом конструктора определенного типа ресурса. Не логичнее ли здесь обычный знак равно? 

Вот тут
```java
dpt model {
    activity callProcessing is callProcessingPattern
}
```
вообще читается что то вроде "активность `callProcessing` есть паттерн `callProcessingPattern`, что вроде как неверно. Но тут не знаю что предложить.

Сами модели пока не запускал, рдо что-то отказался сходу собираться на работе. Постараюсь попозже глянуть.

**Comment by bogachev-pa** [comment]
@kstrizhov 
1. Сейчас точки с запятой ставить можно, но это опционально. Примерно так же сделано в икстенде и это вполне удобно.
По крайней мере мне не хочется заставлять пользователя ставить их. Как вариант писать туториал с ними, но упомянуть, что их можно не ставить. Или наоборот, писать без них, но сказать, что их можно и поставить, если хочется.
2. Согласен, насчет слова `is` у меня тоже сомнения.
Я старался унифицировать в сторону `is`, но, может быть, надо наоборот унифицировать в сторону `=` и от `is` постараться избавиться.

Сейчас:
```erlang
resource aaa is Aaa.create()

sequence bbb is double uniform(12345)

function int ccc is table(int[1..2] a) {
...
}

activity ddd is dddPattern

relevant _eee is Eee.select(...)
```

Если подразумевать `is` как `= new`, то выбиваются активности и, частично, ресурсы, потому что им я сделал создание через метод `create()`. Функции тоже получаются не в тему, потому что у них в скобочках параметры их вызова, а не параметры их конструктора, как в остальных местах. Но касательно функций, у меня есть идеи, как их лучше переделать. Там я избавлюсь от `is` вообще.

С другой стороны, делать все просто через знак равенства, то бросается в глаза отсутствие слова `new`.

Насчет активностей, надо как минимум обязать ставить скобки после имени паттерна, так точно будет логичнее.
```erlang
activity eee is eeePattern()
```
Но вообще тут бы подошло другое ключевое слово, например `calls` или `checks`.
```erlang
activity eee calls eeePattern()
```
Может к активностям нужен какой-то совсем другой подход? Но мне так сразу в голову не приходит.

Суммируя поток сознания выше, наверное, мне хочется сделать так:
```erlang
resource aaa = Aaa.create()

sequence bbb = double uniform(12345)

int table ccc(int[1..2] a) {
...
}

activity ddd checks dddPattern()

relevant _eee = Eee.select(...)
```
Здесь мне не очень нравятся только последовательности, все остальное кажется логичным.

**Comment by kstrizhov** [comment]
>По крайней мере мне не хочется заставлять пользователя ставить их везде.

Зато в коде порядок, всегда знаешь где конец предыдущей мысли и начало следующей :)
>С другой стороны, делать все просто через знак равенства, то бросается в глаза отсутствие слова new.

Ну а что мешает в местах, где необходимо, писать `= new`?
>Но вообще тут бы подошло другое ключевое слово, например calls или checks.

Этот вариант очень неплох на мой взгляд, а вот насчет скобок не понял.

**Comment by aurusov** [comment]
Питон обходится без ```new```, http://stackoverflow.com/a/15081667

**Comment by aurusov** [comment]
В языке ```go``` тип результата функции пишется в конце, как в паскале
https://golang.org/doc/codewalk/functions/

**Comment by AlexChernov** [comment]
> 1 ```Содержание модели``` -> ```Постановка задачи``` (не настаиваю)

Первое, что бросается в глаза. Да и  ```Необходимо подсчитать``` и ```Необходимо промоделировать```  больше подходят под постановку задачи

В первой модели
В пункте ```Описание событий``` событие описано не полностью:
``` erlang
event newCall {
    set execute() {
        techSupport.callCount++;
    }
}
```
Но я попробовал изменить текст, впихнув туда планирование, и у меня вышло только хуже. В прочем я и не настаиваю на изменении. Может просто будет не лишним продублировать полный code-block после слов ```поэтому его также необходимо вызывать в теле метода execute() описанного события``` 

Во второй модели
``` erlang
operation callProcessingPattern {
    relevant _techSupport is techSupport.select(_techSupport.queueLength > 0
            and _techSupport.operatorState == OperatorState.FREE)
```
К сожалению нет возможности проверить сейчас Но вроде должно быть ``` TechSupport.select```

**Comment by bogachev-pa** [comment]
@kstrizhov 
>Этот вариант очень неплох на мой взгляд, а вот насчет скобок не понял.

Паттерн может вызываться с параметрами или без. В случае, если он вызывается без параметров, логичнее ставить пустые скобки, чем не ставить их вовсе.

@aurusov 
1, 2, 3. Поправил.

@AlexChernov 
В первой модели поправил.
Во второй это не ошибка. РДО умеет выбирать релевантные ресурсы как по типу, так и по имени конкретного ресурса, я это там же пояснил. Во втором случае на него так же можно накладывать условия выбора. Т.к. в этой модели ресурс один, то и так, и так будет работать одинаково.

**Comment by bogachev-pa** [comment]
@aurusov 
Добавил страничку с формальным описанием грамматики ресурсов. Приемлемо?

**Comment by aurusov** [comment]
Мне кажется, что это очень важное правило написание хорошего текста: Если можно выкинуть слова из предложения, а смысл при этом не потеряется, но их **надо** выкинуть.
Было
```Здесь Состояние - имя объявленного в модели перечислимого типа.```

Стало 1 
```Здесь Состояние - имя перечислимого типа.```

Стало 1
```Состояние - перечислимый тип.```

А еще лучше вообще ничего не писать, т.к. и так будет понятно
```
enum Состояние {свободен, загружается, готов_к_обработке, работает,разгружается, закончил_обработку};

type Станок {
    int номер;
    Состояние состояние;
    double длительность_обработки;
}
```

**Comment by aurusov** [comment]
Почему после
```
type Станок {
    int номер;
    Состояние состояние;
    double длительность_обработки;
}
```
нет ```;``` ?

**Comment by aurusov** [comment]
```В случае, если ресурс создается в модели глобально и имеет имя, к этому ресурсу можно обратиться по имени в любом месте модели.``` А если он будет удалён ?

**Comment by aurusov** [comment]
```Пример 1:``` -> ```Пример``` - кажется неудобным следить за нумерацией. Может вообще отказаться от этого слова, потому что стилем выделяется.

**Comment by aurusov** [comment]
Удалить бы кавычки ```'*'``` -> ```*```, и добавить стиль, как для примеров

**Comment by aurusov** [comment]
Сама дока отличная, потому что понятная.

**Comment by bogachev-pa** [comment]
Поправил страничку про ресурсы, добавил раздел про удаление ресурса.

>Почему нет ; ?

Ну это же не c++ (:

>А если он будет удалён ?

Ошибка компиляции (в джаве).

>Пример 1: -> Пример - кажется неудобным следить за нумерацией.

Писать `например, ..` мне показалось неудобным, это все-таки формальная справка, а не туториал. Поэтому оставил просто `Пример:` без нумерации.

**Comment by aurusov** [comment]
>>Почему нет ; ?

>Ну это же не c++ (:

Ты же сам признал проблему: https://github.com/aurusov/rdo-xtext/issues/35

**Comment by bogachev-pa** [comment]
Да, и свел все к стилю постановки точек с запятой в джаве. На мой взгляд, он вполне консистентен.

**Comment by bogachev-pa** [comment]
Добавил страничку с описанием событий.

**Comment by aurusov** [comment]
>Да, и свел все к стилю постановки точек с запятой в джаве. На мой взгляд, он вполне консистентен.

Хорошо, давай так оставим

**Comment by aurusov** [comment]
События
- Лучше разбить на два пердложения, под каждым из них свой пример. `Событие может иметь произвольное число параметров. В теле события описываются действия, выполняемые в момент его совершения.`
 - `В теле события описываются операции, например:`
 - `Событие может иметь произвольное число параметров, пример:`
- Не надо использовать слово `действие` в контексте события.
- Я бы убрал слово `Пример` совсем или перенес бы его на строчку выше. Стиль и так показывает, что это пример.
- Удалить
  - ` у требуемого события`
  - ` (если есть)`
- В тексте встречаются  `event` и `currentTime`, но стиль но соблюдается. С этим можно что-то сделать, или парсер не хочет ?

**Comment by bogachev-pa** [comment]
>Не надо использовать слово действие в контексте события.

Кажется, слово `операции` не лучше, оно даже тоже присутствует в названии языка. Другого синонима пока подобрать не могу.

>В тексте встречаются event и currentTime, но стиль но соблюдается. С этим можно что-то сделать, или парсер не хочет?

Не преформатированный код (т.е. не завернутый в теги `<pre></pre>`) он подсвечивать не хочет. С другой стороны, мне кажется, их нераскрашивание в тексте выглядит вполне адекватно.

>Я бы убрал слово Пример совсем или перенес бы его на строчку выше. Стиль и так показывает, что это пример.

Оно позволяет с первого взгляда различить, где примеры, а где формально описание грамматики. В противном случае это несколько сливается. Особенно, если где-то писать слово `Пример` (а где-то это все-таки хочется делать), а где-то не писать.

Остальное поправил.

**Comment by aurusov** [comment]
Ты не прав, операция намного лучше, чем действие. Потому что событие и действие в моделировании совсем разные веще, а операция не введено как понятие вообще. Если смущает операция, то используй слово выражение. В любом случае тут речь идет о стейтмантах и экспрешенах, а не об активитях, как ты написал в начале.

**Comment by aurusov** [comment]
>С другой стороны, мне кажется, их нераскрашивание в тексте выглядит вполне адекватно.

Выглядит плохо, а теги pre добавить нельзя, потому что выпадаем из текста. Так что придется смириться с этим плохим решением, потому что лучше не виже.

**Comment by aurusov** [comment]
>Оно позволяет с первого взгляда различить, где примеры, а где формально описание грамматики. В противном случае это несколько сливается. Особенно, если где-то писать слово `Пример` (а где-то это все-таки хочется делать), а где-то не писать.

В текущей документации есть пример такого плохого места ?

**Comment by bogachev-pa** [comment]
По эвентам:

>В текущей документации есть пример такого плохого места ?

Ну я имел в виду страничку с событиями. Если там убрать слово `Пример` перед первыми двумя примерами, смотрится не очень, на мой взгляд. Может, там немного по-разному оформлять примеры и описание грамматики?

>Ты не прав, операция намного лучше, чем действие. Потому что событие и действие в моделировании совсем разные веще, а операция не введена как понятие вообще. Если смущает операция, то используй слово выражение. В любом случае тут речь идет о стейтмантах и экспрешенах, а не об активитях, как ты написал в начале.

Тут я вас не очень понял. Язык РДО (если мне не изменяет память) расшифровывается как "Ресурсы-Действия-Операции". Ни слово `действие`, ни слово `операция` в том смысле, который они имеют в названии языка не применимы в выражениям внутри тела события. Но оба применимы в другом смысле (т.е. как синонимы выражения). В чем разница между ними?

Из нового:

Добавил страничку константа и результатам.
Написание документации по результатам в очередной раз навело меня на мысль, какие же они у нас странные. Например, почему мы собираем статистику для `watchValue` только в момент удаления какого-то ресурса? Почему не с периодичностью или при каждом изменении значения? Мне кажется, их все надо очень сильно переделать. Не знаю, кому и когда, но пока я придумывал для странички результатов примеры, осознал, что ими очень неудобно пользоваться.

**Comment by aurusov** [comment]
>Ну я имел в виду страничку с событиями. Если там убрать слово Пример перед первыми двумя примерами, смотрится не очень, на мой взгляд. Может, там немного по-разному оформлять примеры и описание грамматики?

Мне наоборот, кажется, что будет легче выглядеть, потому что понятность определяется стилем. Насчет разных стилей для пример и грамматики - не успел предложить, вчера думал о том же. Предлагаю завести совсем разные разные стили для них, но изменить только фон.

>Тут я вас не очень понял. Язык РДО (если мне не изменяет память) расшифровывается как "Ресурсы-Действия-Операции". Ни слово действие, ни слово операция в том смысле, который они имеют в названии языка не применимы в выражениям внутри тела события. Но оба применимы в другом смысле (т.е. как синонимы выражения). В чем разница между ними?

Речь про подходы к моделированию, а не про название программы или языка, который нехило так изменился, где там эти операции сейчас ? Да и название я хотел бы поменять на что-то другое. Подходы
- `событийный`
- сканирование `активностей` (`действие` как перевод слова activity)
- `процессно`-ориентированный

Выделенные слова заняты, их нельзя путать друг с другом. Про это и был мой комментарий. Слово `операция` отсутствует среди них, его можно использовать.

>Из нового:

Еще не смотрел

**Comment by aurusov** [comment]
Вопрос без ответа: https://github.com/bogachev-pa/rdo-xtext/issues/24#issuecomment-12623785

**Comment by aurusov** [comment]
Примеры документаций, где без подписей смотрится отлично
https://pythonspot.com/python-numbers/
http://doc.qt.io/qt-5/qfiledialog.html#details

Пример, где есть четкая структура каждой страницы (у нас не так в принципе)
https://msdn.microsoft.com/ru-ru/library/system.windows.forms.openfiledialog%28v=vs.110%29.aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-2

Там же в непонятном стиле
https://msdn.microsoft.com/en-us/library/windows/desktop/ms633575%28v=vs.85%29.aspx

Я за первый подход.

**Comment by aurusov** [comment]
Константы
- добавь еще примеров
- нужен пример с перечеслимым типом

**Comment by aurusov** [comment]
Результаты
- Список `Тип результата может быть одним из следующих:` не смотрится вообще. Давай попробуем сделдать из него таблицы, чтобы описание было справа

- Пример хочется видеть законченным. Если не хочется его целиком приводить в доке, то нужна ссылка на репу (https://github.com/aurusov/rdo-xtext-models)
- Все показатели можно привести вместе с моделью одним блоком, описание сделать в виде комментариев
- Не хватает значений результатов

**Comment by bogachev-pa** [comment]
>Выделенные слова заняты, их нельзя путать друг с другом. Про это и был мой комментарий. Слово операция отсутствует среди них, его можно использовать.

Done.

>Константы

Done.

>Давай попробуем сделдать из него таблицы, чтобы описание было справа

Сделал. Думаю, стало получше.

>Пример хочется видеть законченным.

Логику работы этого примера я не продумывал вообще. Его написание кажется довольно объемной задачей. Возможно, стоит сделать его одним из пунктов туториала, чтобы убить сразу двух зайцев.

>Все показатели можно привести вместе с моделью одним блоком, описание сделать в виде комментариев

Я так пробовал, мне не очень понравилось. А чем плох текущий вариант?

>Не хватает значений результатов

Добавлю, когда будет готова модель.

**Новое:**

Добавил страничку по последовательностям.
В ней пока не хватает еще нескольких примеров и нужно поправить подсветку слова `histogram`.

**Comment by aurusov** [comment]
Остались слова `пример`

Было
![2015-08-15 12 21 33](https://cloud.githubusercontent.com/assets/5585202/9288294/80f42052-4348-11e5-80da-05e85015a7cb.png)

Стало
![2015-08-15 12 23 39](https://cloud.githubusercontent.com/assets/5585202/9288295/85637138-4348-11e5-9694-ac5f162f8e9b.png)

**Comment by aurusov** [comment]
>>Все показатели можно привести вместе с моделью одним блоком, описание сделать в виде комментариев

>Я так пробовал, мне не очень понравилось. А чем плох текущий вариант?

Мельтешение стилей на единицу площади. Переделал, мне так больше нравится.

**Comment by aurusov** [comment]
Решил сам поправить, потому что проще самому экспериментировать, чем описать эксперимент. Мое итого
- убрать слово `пример`
- подсветка `histogram`
- доделать `sequence`

**Comment by bogachev-pa** [comment]
>Вопрос без ответа: #24 (comment)

Можете процитировать, если он все еще без ответа? Ссылка не работает у меня почему-то.

**Comment by aurusov** [comment]
>>Вопрос без ответа: #24 (comment)

>Можете процитировать, если он все еще без ответа? Ссылка не работает у меня почему-то.

Ссылку не полностью скопипастил
https://github.com/bogachev-pa/rdo-xtext/issues/24#issuecomment-126237855

>у параметров столбцы оказываются невыровненными:

Не представляю, как это можно выровнять в текущей схеме. Предлагаю оставить, потому что выравнивание стало не хуже.

>И вообще табличка разбухла из-за оформления параметров таблицей, мне больше нравилось, как было до этого.

Мне тоже. Пытался это подправить, но наткнутся в стилях на
- https://github.com/bogachev-pa/rdo-xtext/blob/feature/grammar_reference/docs/styles/rao_general.css#L266
- https://github.com/bogachev-pa/rdo-xtext/blob/feature/grammar_reference/docs/styles/rao_general.css#L273

Получается, что надо заводить разные стили для внешней и вложенной таблиц. Поигрался немного с одним стилем, но решил не париться. Если хочешь, то предложи решение. На разных стылях будет `ok`, просто мне показалось излишне сложным.

**Comment by bogachev-pa** [comment]
>Ссылку не полностью скопипастил

Забыл отписаться по этому поводу. Я за то, чтобы сделать разные стили для синтаксиса и кода, но пока этого не сделал, т.к. не очень умею в `css`.

>Не представляю, как это можно выровнять в текущей схеме. Предлагаю оставить, потому что выравнивание стало не хуже.

Стало хуже то, что табличка стала неоправданно больше по размеру. Было вот так:
![screenshot from 2015-08-19 10 19 31](https://cloud.githubusercontent.com/assets/6528492/9350733/e302b86a-465b-11e5-90fc-c29dda1dee24.png)

Она хотя бы умещалась у меня полностью на экране. Имена параметров тоже в ней не теряются, т.к. выделены другим стилем.

**Comment by bogachev-pa** [comment]
В свою очередь остались без ответа мои рассуждения по поводу результатов:
>Написание документации по результатам в очередной раз навело меня на мысль, какие же они у нас странные. Например, почему мы собираем статистику для watchValue только в момент удаления какого-то ресурса? Почему не с периодичностью или при каждом изменении значения? Мне кажется, их все надо очень сильно переделать. Не знаю, кому и когда, но пока я придумывал для странички результатов примеры, осознал, что ими очень неудобно пользоваться.

**Comment by aurusov** [comment]
>Она хотя бы умещалась у меня полностью на экране. Имена параметров тоже в ней не теряются, т.к. выделены другим стилем.

Проблема решается стилем, написал же. Откат изменений - это маскировка проблемы. Рано или поздно могут понадобиться вложенные таблицы. И оно будут большими.

**Comment by aurusov** [comment]
>В свою очередь остались без ответа мои рассуждения по поводу результатов:

Оформи мысли в виде таски. Может быть из задачи получится курсовой.

**Comment by bogachev-pa** [comment]
>Оформи мысли в виде таски. Может быть из задачи получится курсовой.

Готово: https://github.com/aurusov/rdo-xtext/issues/123

**Comment by bogachev-pa** [comment]
Возник вопрос насчет приоритета точек принятия решений. Цитирую старую справку:
>В процессе сканирования активностей дочерние точки принятия решений имеют приоритет перед активностями внутри точек типа some, но не имеют таковой в точках типа prior. В последних все содержимое точки сортируется по приоритету на каждой итерации поиска.

Я правильно понял, что это значит, что даже при равном приоритете для `prior` просканируются сначала все активности родительской точки, и только потом дочерней? Строго говоря, выходит, что `prior` не являлись надмножеством `some`?

**Comment by aurusov** [comment]
Приоритет надо смореть в старом коде, не помню. Посмотришь ? Но вспомнил другую важную разницу.
В `prior`
- все активности должны быть проверены на условие
- потом расчитан приоритет для каждой
- потом сортировка по приоритету
- потом вызов одной

В `some`
- вызывается первая, у которой выполняется условие

Т.е. `some` намного быстрее должна работать.

**Comment by bogachev-pa** [comment]
Про подмножество имел в виду, что `some` - частный случай `prior`. Однако это может быть не так.

Про другую важную разницы мы с вами обсуждали и пришли к выводу, что это не кажется узким местом в системе и лучше их объединить. В будущем, возможно, стоит попрофилировать.

Код посмотрю вечером.

**Comment by aurusov** [comment]
Чё-то подумал, насчитал разную вычислительную сложность. Т.е. понятно и без профилятора. Худший случай:

`some` = `O(N) -> O(N)`
`prior` = `O(N) + O(N) + O(N*logN) -> O(N*logN)`

**Comment by bogachev-pa** [comment]
А в чем смысл сначала проверять все активности на условие, а потом их сортировать? Я понимаю, что алгоритмическая сложность от этого не меняется, но все же.

**Comment by aurusov** [comment]
Ты предлагаешь выполнять активность, условие которой не выполняется ? Или сначала расчитать значения всех приоритетов, отсортировать, и только потом искать первую подходящую ? Если второе, то разницы нет imho.

**Comment by bogachev-pa** [comment]
Оглавление теперь генерируется скриптом.

**Comment by aurusov** [comment]
Я думал, что ты [просканируешь](http://stackoverflow.com/a/21459809/5138658) рекурсивно папки на предмет `*.html`, вырежешь из них `<h2>` и сформируешь оглавление. Тогда добавление стало O(1). Текущее решение O(N), где N - кол-во новых страниц документации. Но оно тоже ok, потому что раньше не было никакого.

PS: я вообще не уверен, что js может получить доступ к файлам на винте.

**Comment by aurusov** [comment]
Насколько просто в твоем решении добавить вложенность оглавления ?

**Comment by bogachev-pa** [comment]
>я вообще не уверен, что js может получить доступ к файлам на винте.

Не может, именно поэтому и пришлось делать так.

>Насколько просто в твоем решении добавить вложенность оглавления?

Если знать js - по идее должно быть элементарно. Мне лично придется повозиться, но, кажется, тоже не очень сложно.
