### ISSUE TITLE
Исправить конфигурацию сериализации ресурсов в новой грамматике

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/rdo-xtext#25]
Так как способы создания ресурсов были переработаны, необходимо продумать, каким образом конфигурировать, каким образом отмечать, что их нужно сериализовать.

**Comment by aurusov** [comment]
Перестало работать старое окошко с чекбоксами ? Совсем, частично ?

**Comment by bogachev-pa** [comment]
Частично, только в некоторых случаях с ресурсами.
Скрины сейчас показать не могу, но если вкратце:
1. Для ресурсов, созданных при инициализации модели, и не имеющих имен (теперь так можно: просто пишем `Парикмахерская.create(0)`), в дереве отображается `null`. 
2. Ресурсы, созданные в паттерне, теперь нигде не отображаются, так как это теперь просто конструкция в теле паттерна (`Клиенты.create(Состояние_клиента.Пришел, Тип_клиента.Тип_2)`), они не подбираются как релевантные. На этот счет у меня есть еще вопросы и соображения, например, зачем мы вообще отмечаем галочками релевантные ресурсы паттернов? Кажется, что это имело смысл именно для случая создания ресурса в паттерне, а для остальных случаев этот какой-то не очень реальный сценарий.

**Comment by aurusov** [comment]
Выглядит как стандартная проблема трассировки временнго ресурса. Т.е. ресурса, у которого нет имени, а только тип. Вот по типу и надо мышкой клацать imho.

**Comment by bogachev-pa** [comment]
Я сделал так:
1. Безымянные ресурсы, создаваемые глобально, отображаются в дереве с галочками в формате тип[номер].
2. Паттерны и эвенты не имеют никаких вложенных элементов в дереве. Паттерн/эвент отмечен - все операции с релевантными ресурсами и создание ресурсов в нем сериализуется. Схема с внутренними галочками вполне реализуема, но она выглядела довольно странно в случае, если ресурсы создавались во всяких вложенных выражениях и т.п. Поэтому я решил упростить.

Нерешенной (нерешаемой?) осталась одна проблема: как отследить изменение параметров ресурсов, не отбираемых как релевантные, и не создаваемых в паттерне?

**Comment by aurusov** [comment]
2 выглядит всетаки странным, но давай поживем с таким подходом.

>как отследить изменение параметров ресурсов, не отбираемых как релевантные, и не создаваемых в паттерне?

Вот тут совсем не понял. По остаточному принципу такие ресурсы могут быть созданы в rss, а этот кейс покрыт. Поясни на примере.

**Comment by bogachev-pa** [comment]
Галочки в дереве относятся к внутренней проверке в базе данных, когда у нее вызывают метод "добавить запись ресурса", например. С этим проблем нет. Проблема в том, когда вызывать этот самый метод. Сейчас он вызывается в конце выполнения паттернов/эвентов для всех релевантных ресурсов и для каждого создания ресурса в паттерне/эвенте.

Пример:

```erlang
rule myPat() {
    relevant rel1 = Type_1.select(rel1.param1 > 0); // <- изменения отследятся
    set execute() {
        Type_2.create(*); // <- изменения отследятся
        Res_1.param_2++; // <- изменения не отследятся
        Res_1.param_3--; // <- аналогично
    }
}
```

Но отследить просто обращение к параметру ресурса довольно сложно. Точнее, возможно, но, так тогда - отдельная запись для любого изменения параметра? Мы могли в паттерне поменять пять разных параметров одного ресурса и у нас появится тогда пять записей. Альтернативно можно отслеживать, у каких ресурсов вообще менялись в ходе выполнения паттерна параметры, и по окончанию паттерна сериализовать их все. Пока не уверен, насколько просто реализовать.

**Comment by aurusov** [comment]
Без ответов на эти вопросы у нас не должно быть трассироки, но она есть. Если кратко, то писать только одну запись на один ресурс в конверторе, т.е. на операцию две записи на ресурс, если он менялся. Это до сих пор нерешенный вопрос ? Или я чего-то не понимаю.

**Comment by bogachev-pa** [comment]
Операция пристаивания ресурсу значения это просто одна из конструкций на языке выражений, а не какое-то особое грамматическое правило, так что ее довольно трудно отследить. Поэтому отслеживаются сейчас только изменения релевантных ресурсов и создания ресурсов, т.к. эти конструкции имеют свои особые грамматические правила.

Возможно, лучше обсудить голосом.

**Comment by aurusov** [comment]
Правильно ли я понял, что
- мы не умеем детектить изменения нерелевантных ресурсов, и, например, писать по ним трассироку и делать графики ?
- мы можем лишний раз записать в трассироку релевантный ресурс, которые НЕ поменялся в паттерне ?

Если так, то это отстойно. Весело про такое узнать только сейчас.
- или научиться перекрывать присвоивание
- или научиться через подсчет хеша сравнивать слепки баз данных, что медленно

При это я не понимаю, в чем разница между отслеживанием изменений в релевантных ресурсах и в нерелевантных.

**Comment by bogachev-pa** [comment]
Да по обоим пунктам.

>или научиться перекрывать присваивание

Попробую сделать это. Такого понятия, как "слепок базы данных" у нас вообще нет. Если не выйдет, подумаю, как это принципиально отрефакторить.

Возможно, следует запоминать все ресурсы, состояние которых изменилось, и вносить их в базу данных в определенных точках ( = окончание каждого конвертора?).

>При этом не понимаю, в чем разница между отслеживанием изменений в релевантных ресурсах и в нерелевантных.

Собственно, отслеживаний изменений нет, просто состояние всех релевантных ресурсов добавляются в БД и все.

**Comment by aurusov** [comment]
Ага, теперь сходится.

>Такого понятия, как "слепок базы данных" у нас вообще нет

Т.е. мы не можем написать что-то типа ```model.getResources()``` и получить список всех ресурсов, приведенных к базовому классу ?

**Comment by aurusov** [comment]
Текущее обсуждение ушло в сторону от темы.  Вот тут начали обсуждать уже новую тему
https://github.com/bogachev-pa/rdo-xtext/issues/25#issuecomment-107145746. Кажется, что это несвязанные задачи. Предгаю разнести по разным таскам.

**Comment by bogachev-pa** [comment]
>Т.е. мы не можем написать что-то типа model.getResources() и получить список всех ресурсов, приведенных к базовому классу ?

Из сгенерированного кода можно. Из либы за константое время нет.

Отдельную таску завел: https://github.com/bogachev-pa/rdo-xtext/issues/31

Тогда эту закрываю, потому что с деревом все исправлено.
