### ISSUE TITLE
Реорганизовать файлы проектов

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/rdo-xtext#27]
@aurusov
@k-alexandrovsky
@LeKaitoW
@kstrizhov

Сейчас:
- `rdo` - проект, содержащий классы, необходимые для кодогенерации
- `rdo.lib` - проект, содержащий женерик классы, используемые сгенерированным кодом, а также всю прослойку между базой данных и графическим интерфейсом
- `rdo.ui` - проект, содержащий классы графического интерфейса

Я думаю, нужно как минимум вынести всю прослойку в отдельный проект, и, может быть, внутри проектов как-то разбить все более логично по пакетам.

Как минимум что должно быть по проектам:
- `rdo` - без изменений
- `rdo.lib` - только классы, которые необходимы рантайму. `Database` в их числе.
- `rdo.ui.helpers` - как назвать? Сделать отдельным проектом или пакетом внутри проекта `ui`? Туда отправятся всякие трейсеры и прочая прослойка между базой данной и уи. Т.е. все классы, что предоставляют информацию о ходе моделирования для уи.
- `rdo.ui` - без изменений

Если есть какие мнения на этот счет, высказывайте.

Цитируя начало обсуждения:

>Что значит не хочется. Если нода - это часть базы, то текущее решение выглядит ошибочным, потому что не отражает эту мысль. Видимо неясно выразился. Я не предлагаю сделать Node частью класса Database. Предлагаю, чтобы все классы базы жили в ПАПКЕ database.
>```
ru.bmstu.rk9.rdo.lib.database.Query
ru.bmstu.rk9.rdo.lib.database.Node
ru.bmstu.rk9.rdo.lib.database.Subscriber
```
>и т.д.

**Comment by aurusov** [comment]
Мне кажется, что названия пакетов
- ```lib```
- ```helpers```
- ```tools```
- ```common```
- ```mics```
- ```utils```

имеют очень общее название, а значит маскируют проблему - это помойка, в которой не разобрались да так и оставили. Как вариант
- Вынести всё содержимое ```rdo.lib``` в пакеты с читаемыми названиями. Например, ```rdo.database```. То что не получится свалить в помоечку ```rdo.common```. Саму ```rdo.lib``` удалить.
- Классы-хелперы распологать рядом с классами, для которых они хелперы. Если потом их будет много и их захочется объеденить, то эта хотелка и подскажет имя пакета.
- Я бы вынес генерацию кода из корня в ```rdo.language``` или ```rdo.compiler```. Это и другие названия обсуждаемы, даны для примера.

В общем я так вижу систему, не видя её кода.

**Comment by bogachev-pa** [comment]
Разнес все классы в `lib` по папочкам. К сожалению, т.к. джава считает их всех отдельными пакетами, то область видимости во многих местах пришлось увеличить до `public`, а где-то добавить публичных геттеров и сеттеров.

**Comment by aurusov** [comment]
Увеличение видимости до public и добавление геттеров/сеттеров как раз верное решение. Теперь то, что осталось в private стало по настоящему таким. Связанность уменьшилась и стала явной.

**Comment by bogachev-pa** [comment]
Отрефакторил структуру проекта `ui`.
Осталось несколько вопросов:
1. Надо ли разбить пакет `ui.runtime` на более мелкие?
2. В ходе рефакторинга вскрылось несколько проблем в дизайне. Из-за них я пока не могу переместить классы `Tracer`, `TreeBuilder` и `SerializationConfig` в `ui`, хотя они должны находиться именно там (насчет `SerializationConfig` есть еще некоторые сомнения, скорее всего он должен быть разбит на два класса, один из которых отправится в `ui`, а второй останется в либе).
Вероятно, решение проблем с этими классами зависит от решения вот этой задачи: https://github.com/bogachev-pa/rdo-xtext/issues/30. Собственно, вопрос, продолжаю в этой же ветке?

**Comment by aurusov** [comment]
1 Выглядит как свалка. Есть понимание на что можно разбить ?
2 Эта таска ссылается на #30, а она на эту, рекурсия. Так что поступи как удобно. Может будет проще разделить их на две. Я готов оперативно рассматривать комиты, чтобы эту задачу закрыть быстро. Т.е. я предлагаю #27 -> пулреквест -> #30 -> пулреквест -> продолжение #27.

**Comment by bogachev-pa** [comment]
>1 Выглядит как свалка. Есть понимание на что можно разбить ?

Думаю, как минимум на `build` и `simulation` и отправить `TraceExportHandler` в `trace`. Пока не знаю, стоит ли разбивать сам `simulation`, там будет около 6-7 классов, связанных с сборкой/запуском/остановкой модели и управлением прогоном (режим, скорость и т.п.). Может, стоит разбить как раз по этому "и".

>Т.е. я предлагаю #27 -> пулреквест -> #30 -> пулреквест -> продолжение #27.

Согласен. Можно даже обойтись без третьего пул-реквеста, и перенести два класса из либы в уи в рамках #30.
Тогда я разберусь в `SerializationConfig` в этом пул-реквесте, а `Tracer` и `TreeBuilder` оставлю здесь как есть.

**Comment by aurusov** [comment]
1 Если есть понимание, то конечно надо

**Comment by bogachev-pa** [comment]
Поправил замечания, вынес `SerializationConfig` в `ui`, переформировал пакет `simulation`.
В принципе, мне теперь нравится структура `ui`.

**Comment by bogachev-pa** [comment]
Убрал пакет `lib.common`, т.к. не очень информативное название.

**Comment by bogachev-pa** [comment]
Пул-реквест ставить на `release/current` или ветку с версией?

**Comment by aurusov** [comment]
Конечно в `release/current`

**Comment by bogachev-pa** [comment]
Ну формально мы поломали совместимость по расширению моделей, потому и спрашиваю.

**Comment by aurusov** [comment]
Ставь как договорились, но поясни про поломку.

**Comment by bogachev-pa** [comment]
Ну, модель теперь должна называться `barber.rao`, а не `barber.rdo`.

**Comment by aurusov** [comment]
А, не подумал.

**Comment by aurusov** [comment]
Закроешь или что-то осталось ?

**Comment by bogachev-pa** [comment]
Пока оставлю. Закончу вместе с рефакторингом нотификаций (в принципе уже сделал это, но еще не залил, т.к. недоделал другие вещи).

**Comment by aurusov** [comment]
Как это связано с нотификациями ?

**Comment by bogachev-pa** [comment]
Они блокировали переезд некоторых файлов. А переезд блокировал часть рефакторинга нотификаций.

**Comment by aurusov** [comment]
Ага, вспомнил. Т.е. после нотификации еще будут небольшие изменения в расположении файлов ?

**Comment by bogachev-pa** [comment]
Да, переедут два файлика, которые недопереехали в основной части этого рефакторинга.

**Comment by bogachev-pa** [comment]
Закончено вместе с рефакторингом нотификаций.
