### ISSUE TITLE
Выбрасывать исключения вместо возврата null'ов в случае внутренних ошибок

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/rdo-xtext#28]
Начало обсуждения тут:
https://github.com/k-alexandrovsky/rdo-xtext/pull/37#discussion_r31344850

Мне кажется, лучше и проще всего будет во всем местах, где `return null` означает внутреннюю ошибку в системе, писать 
```java
throw new RuntimeException("<описание внутренней ошибки>")
```
а все проверки
```java
if (returnValue != null)
```
 в методах, куда этот `null` мог вернуться, убрать. Тогда в случае внутренней ошибки ее будет максимально легко отловить и понять.

Вроде бы именно такой подход является общепринятым в джаве, хотя я, конечно, не уверен.

@k-alexandrovsky
Кирилл, что думаешь по этому поводу?

Обратить внимание:
https://github.com/aurusov/rdo-xtext/pull/59#discussion_r33595773

**Comment by aurusov** [comment]
Ответил там же https://github.com/k-alexandrovsky/rdo-xtext/pull/37#discussion_r31606223
Потому что https://github.com/k-alexandrovsky/rdo-xtext/pull/37#discussion_r31606505

**Comment by aurusov** [comment]
Лучше наследоваться от RuntimeException. В графиках будет свой класс runtime-ошибок, в БД - свой.

**Comment by bogachev-pa** [comment]
Тогда создаем отдельные папки в духе `ui.exception` и `lib.exception`, где будем эти классы описывать?

**Comment by aurusov** [comment]
Ты думаешь, что ТИПОВ будет много ? Не путаешь ТИП с разными сообщениями об ошибках в рамках одного ТИПА ? Например,
```java
new throw MyException("la-la");
new throw MyException("bla-bla");
```

**Comment by bogachev-pa** [comment]
Ну да, я так и подумал. Вот [тут](https://github.com/k-alexandrovsky/rdo-xtext/pull/37#discussion_r32108665) вы предлагаете `ModelStructureError`. Аналогично может быть `DatabaseParsingError`, `PlotError`, `GraphError` и т.д. (вообще, я думаю, надо использовать слово `Exception` вместо слова `Error`, т.е. `InvalidModelStructureException`).

Или вы хотите обойтись двумя классами - для либы и для гуи?

**Comment by aurusov** [comment]
Никаких ограничений, только логика задачи. Просто я думал, что ```PlotException``` будет жить в своём пакете ```plot```, а не в общей куче. И т.д. В ощем пусть будут папки.

**Comment by aurusov** [comment]
Чтобы не потерялось
https://github.com/k-alexandrovsky/rdo-xtext/pull/37#discussion_r32114369

**Comment by bogachev-pa** [comment]
А, понял. Получается, тут мы зависим от задачи рефакторинга структуры проекта.

Я предлагаю пока сделать две отдельных папки для `lib` и `ui`, потому что это будет логичнее с текущей структурой, а потом, если структура будет такова, что пакеты будут разбиты по типу `plot`, `trace`, `graph`, `db` и т.п. - делать по одному классу исключения в каждом пакете.

**Comment by aurusov** [comment]
Да, зависимость есть. Но даже после рефакторинга может оказаться по нескольку классов исключений. Зависит от хотелок на стороне обработчиков. Не будем же мы по тексту их различать.

**Comment by aurusov** [comment]
Посмотри вопросы в https://github.com/k-alexandrovsky/rdo-xtext/pull/37#discussion_r32114369

**Comment by bogachev-pa** [comment]
Готово.

**Comment by aurusov** [comment]
Оно, ставь пул-реквест как рефакторинг.
