### ISSUE TITLE
Унифицировать схему нотификации гуи об изменениях в базе данных

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/rdo-xtext#30]
Связана с https://github.com/bogachev-pa/rdo-xtext/issues/27

В данный момент для нотификации каждого из компонентов гуи об изменениях в базе данных используются отдельный субскрайбер и отдельный таймер (для нотификаций в процессе прогона).

Нужно сделать единый таймер для компонентов, не требующих особо быстрых обновлений (т.е. почти всех, кроме анимации), и, возможно, какой-то общий канал взаимодействия с бд.

**Comment by bogachev-pa** [comment]
@aurusov 
Пока что не могу придумать правильный дизайн для нотификаций.

Сейчас схема нотификаций такая: у симулятора, базы данных и ресурсов есть свой [`NotificationManager`](https://github.com/aurusov/rdo-xtext/blob/release/current/ru.bmstu.rk9.rao.lib/src/ru/bmstu/rk9/rao/lib/notification/NotificationManager.java). Они инициализируют его массивом строк - категориями нотификаций. Все, кому надо, регистрируются в нем на определенную категорию и получают уведомления, когда хозяин менеджера вызывает у него метод `notifySubscribers()`.

Мне все здесь нравится, но для гуи хочется одновременных обновлений всех компонентов и какого-то единого апдейтера.

Как вам такой вариант?

Имеем некий статический класс, например, `UiNotifier`, который регистрируется на все подписки базы данных и симулятора. `UiNotifier` предоставляет такой же (а, может, и другой) набор категорий, на которые регистрируются уже все компоненты `ui`. При этом в `UiNotifier`'е можно зарегистрироваться как на обновление в начале и конце моделирования, так и на обновление в реальном времени - для этого будет общий таймер (или два - быстрый и обычный).

**Comment by aurusov** [comment]
Обсудили по скайпу.

**Comment by aurusov** [comment]
1. Базовый подписчик по категориям, уведомляет сразу. Доступен всем желающим.
2. Подписчик по категориям и таймеру. Подписывается как клиент на (1), но отправляет уведомления, только когда протикает таймер. В текущей схеме может не иметь настроиваемого таймера, т.к. он должен быть одинаков для всех UI компонент. По крайней мере так кажется. Константа подбирается на глаз от 1/25 секунды до 1/60.

**Comment by bogachev-pa** [comment]
Реализовал описанную схему.
Осталось включить в эту схему обновление графов (у них немного отличается существующая схема нотификаций, поэтому не сделал сразу).

**Comment by bogachev-pa** [comment]
Еще остался вопрос по гитфлоу:
Получается, мне сейчас нужно бранч `2.1.1` переименовать в `2.1`, замержить его в мастер (ну и мастер в релиз карент) и потом поставить пул-реквест вот этого бранча на новый бранч `2.2`?

**Comment by aurusov** [comment]
>Осталось включить в эту схему обновление графов (у них немного отличается существующая схема нотификаций, поэтому не сделал сразу).

Т.е. графы сейчас работают на старой схеме ?

**Comment by aurusov** [comment]
>Получается, мне сейчас нужно бранч `2.1.1` переименовать в `2.1` (или `2.2`? `2.1` ведь уже существовала), замержить его в мастер (ну и мастер в релиз карент) и потом поставить пул-реквест вот этого бранча на новый бранч `2.2`?

Вообще все не так. Тут несколько ошибок
- Надо было создать 2.1, вместо 2.1.1
- Когда стало понятно, что на подходе новая фича. Она однимает версию до 2.2. Значит 2.1 *удаляется*, все, чтобы было в неё подмержено, мержится в 2.2. Потом в мастер, потом в карент-релиз, и только так.
- Я не уверен, что это фича. Это рефакторинг. Вот что ты напишешь в описании релиза ? Что для пользователя изменилось ? Поэтому надо создать 2.1, в которую включается всё. А финальная версия 2.1.1.

**Comment by bogachev-pa** [comment]
>Т.е. графы сейчас работают на старой схеме ?

Пока что да.

Создал пул-реквест, чтобы было удобнее смотреть.
