### ISSUE TITLE
Исправить схему добавления записей об изменении ресурсов в базу данных

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/rdo-xtext#31]
Начало обсуждения тут: https://github.com/bogachev-pa/rdo-xtext/issues/25#issuecomment-107145746

Вкратце:
- мы не умеем детектить изменения нерелевантных ресурсов, и, например, писать по ним трассироку и делать графики
- мы можем лишний раз записать в трассироку релевантный ресурс, которые НЕ поменялся в паттерне

**Comment by bogachev-pa** [comment]
Рабочая схема будет такой:
- перед выполнением любого конвертора запоминаем состояние базы данных аналогично тому, как это делается для `DecisionPointSearch`
- по окончании выполнения конвертора сравниваем новое состояние базы с исходным и записываем в БД все ресурсы, состояние которых поменялось

Получается очень универсальная схема, совершенно независящая от грамматики или чего-то еще.

**Comment by bogachev-pa** [comment]
@aurusov
В итоге заимплементил другую схему (более удобную и, кажется, с меньшей алгоритмической сложностью):

1. Каждое создание/изменение/удаление ресурса запоминается в списке в базе данных.
2. В момент завершения любого паттерна или события (тех, кто может менять состояние бд) содержимое списка отпраляется в базу данных, а сам список очищается.

Есть вопрос по фильтрации этого списка от дубликатов.
Проблема такая, например, в паттерне у ресурса изменилось два параметра. Соответственно, в список попадет две записи об изменении состояния данного ресурса. Чтобы это не попало в базу данных, я подобные дубликаты удаляю и храню только по одной записи каждого типа (`Created`, `Altered`, `Removed`).
Мне это кажется, логичным, но это не совсем соответствует старому РДО, где для ресурса всегда добавлялась только одна запись в паттерне (например, ресурс был создан, а потом изменен, в старом РДО будет только одна запись `Created`, а у меня сейчас будет запись `Created` с начальными параметрами ресурса, и запись `Altered` с состояниями ресурса на конец события).

Как вам кажется более правильным?

**Comment by aurusov** [comment]
Выглядит отлично. Раньше мы вообще такое не могли делать в одном паттерне из-за статусов конверторов. Поэтому и не отличали такое. Ну могли, теоретически, создание и изменений посмотреть. В общем сейчас лучше, давай так оставим.

>1. Нужно ли вообще нам отображать создание, изменение и моментальное удаление ресурса в трассировке. (строчки 1-3 трассировки)

Да

>2. Нужно ли отображать изменение ресурса, если потом он будет удален (нужна ли строчка 2, если есть строчка 3). 

Да

**Comment by bogachev-pa** [comment]
Окей.
