### ISSUE TITLE
Чистка кода в проекте кодогенерации

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/rdo-xtext#32]
- дать всем переменным читаемые имена
- использовать автоматическое форматирование для файлов `xtend`

**Comment by aurusov** [comment]
А разве можно настроить автоматическое форматирование для этого типа файлов ?

**Comment by bogachev-pa** [comment]
Можно, но, естественно, только самого кода на `xtend`, а не кода на джаве, который мы генерируем.

**Comment by aurusov** [comment]
Вряд ли. Переносов нет, но оно и к лучшему. Код очень вытянут по горизонтели.

**Comment by bogachev-pa** [comment]
Не очень понял, вряд ли что?

**Comment by aurusov** [comment]
Вот к чему

>Собственно, там дефолтный стиль форматирования такой же, как джавовский.

У последнего в строке 80 символов. Код xtext'а явно шире.

**Comment by bogachev-pa** [comment]
>У последнего в строке 80 символов. Код xtext'а явно шире.

Да, там действительно 120.

**Comment by aurusov** [comment]
И это нормально смотрится в среде, но отвратительно ревьювится на гитхабе.

**Comment by bogachev-pa** [comment]
На мой взгляд это так же неудобно в среде. Дело привычки, конечно, но я мне удобно иметь два открытых рядом экрана и при размере строки в 120 это довольно неудобно. Может, сделать 80 или 100?

**Comment by aurusov** [comment]
Именно дело привычки. Поэтому давай оставим стандартные настройки.

**Comment by bogachev-pa** [comment]
Готово. Отправил пул-реквест: https://github.com/aurusov/rdo-xtext/pull/71
