### ISSUE TITLE
Убрать префикс `RDO` у всех классов проекта

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/rdo-xtext#33]

**Comment by bogachev-pa** [comment]
@aurusov 
Пока переименовывал возник вопрос: допустим, есть вот такой класс
```java
public class RDOLinkingDiagnosticMessageProvider extends
		LinkingDiagnosticMessageProvider {
...
}
```
Как с ним лучше поступить? Назвать `LinkingDiagnosticMessageProvider` и пусть отличаются только путем? Я просто не уверен, что это хорошая практика для классов, которые могут оказаться частью `API`.

**Comment by aurusov** [comment]
1 Можно оставить префикс. Мы как бы говорим, что расширяем стандартный класс для нашего плагина/программы. В идеальном мире префикс должен быть по имени программы. Т.е. не `RDO`, а `RAOXT`. Но сейчас сойдет и `Rdo`, но только вот в таком написании, не надо делать все буквы большими.
2 Если убрать префикс, то начнутся конфликты с типами Java или x-text'а ?

**Comment by bogachev-pa** [comment]
>Если убрать префикс, то начнутся конфликты с типами Java или x-text'а ?

Нам придется обращаться к ним вот так, например: `rdo.Double`.

**Comment by aurusov** [comment]
>Может, тогда `Rao`, как название языка?

Давай

>Нам придется обращаться к ним вот так, например: `rdo.Double`.

Выглядит читаемым, но мы поменяли префикс на префикс с точкой. Но мне точка больше нравится.

**Comment by bogachev-pa** [comment]
>Выглядит читаемым, но мы поменяли префикс на префикс с точкой. Но мне точка больше нравится.

Оказалось, для некоторых из таких классов конфликты будут еще на уровне грамматики с терминалами вроде `INT`. Т.е. не выйдет так сделать.

**Comment by aurusov** [comment]
Значит у всех типов для единообразия нужно сделать одинаковый префикс `Rao`

**Comment by bogachev-pa** [comment]
Я сейчас сделал все очень радикально и переименовал `rdo` в `rao` вообще везде, включая имена проектов, название языка и прочее. Т.е. чтобы все заработало после этого коммита надо заново поимпортить проекты и все такое.

Стоило это сейчас делать или я зря? Дело в том, что некоторые классы автоматически генерятся икстекстом и получаются имена с префиксом `RDO`. Получается путаница `RDO`/`Rao`.

**Comment by aurusov** [comment]
Правильно. Насчет импорта не понял.

**Comment by bogachev-pa** [comment]
Проекты все переименовались, а вы в эклипс импортили другие проекты с другими именами. Надо будет по инструкции заново все сделать после этого коммита.

**Comment by aurusov** [comment]
Ну это фигня.
