### ISSUE TITLE
Планы на дипломный проект

### ISSUE THREAD

**Issue by bogachev-pa** [bogachev-pa/rdo-xtext#37]
@aurusov

Собственно, что я планирую сделать за лето:
1. Доделать документацию (в частности оформление - встроить в эклипс и т.п.)
2. Порефакторить весь код. Туча тасок в моем форке.
3. Настроить систему тестирования.

Какие я вижу задачи на осенний семестр:
1. Прореживание графиков (вроде обсуждали).
2. Есть идея запилить своп базы данных на диск, чтобы мы не умирали по памяти при моделировании. Что думаете на этот счет?
3. Нужно провести переход на иксбейз.

**Comment by aurusov** [comment]
>Собственно, что я планирую сделать за лето:

Про лето всё ok, только я бы расставил приоритеты так
1. критическая задача
2. важная, делается параллельно первой, но не забывает, что она вторична
3. конечно нужная, но я бы вынес её от сюда, в пул самых важных задач и не приступал бы к ней пока не будет 1 и 2. И вообще она может пойти кому-то на курсач.

>Какие я вижу задачи на осенний семестр:

Тут я бы сильно поменял приоритету
1. Прореживание графиков (вроде обсуждали). - Это хороший курсач, а тебе надо думать над дипломом
2. Есть идея запилить своп базы данных на диск, чтобы мы не умирали по памяти при моделировании. Что думаете на этот счет? - Надо исследовать. Может быть исследовательской частью диплома. Но глобаль попахивает разработкой своей СУБД. Кажется важным вовремя перейти к кокой-то существующей СУБД.
3. Нужно провести переход на иксбейз. - просто блокирующая задача

**Comment by bogachev-pa** [comment]
Думаю, таска уже не нужна.
